name: cassandra-cluster
services:
    cassandra-node-1:
        image: cassandra:5.0
        container_name: cassandra-node-1
        environment:
        - CASSANDRA_USER=cassandra
        - MAX_HEAP_SIZE=768M
        - HEAP_NEWSIZE=256M
        - CASSANDRA_CLUSTER_NAME=cassandra-cluster.rgorosti.local
        - CASSANDRA_SEEDS=CompuAndre.local:7001,CompuAndre.local:7002,CompuAndre.local:7003
        - CASSANDRA_LISTEN_ADDRESS=auto
        - CASSANDRA_RPC_ADDRESS=0.0.0.0
        - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
        - CASSANDRA_NATIVE_TRANSPORT_PORT=9041
        - CASSANDRA_STORAGE_PORT=7001
        - CASSANDRA_SSL_STORAGE_PORT=7501
        - JVM_OPTS=-Xms256M -Xmx768M -Dcassandra.native_transport_port=9041 -Dcassandra.storage_port=7001
            -Dcassandra.ssl_storage_port=7501 -Dcassandra.broadcast_rpc_address=CompuAndre.local
            -Dcassandra.broadcast_address=CompuAndre.local -Dcom.sun.management.jmxremote.authenticate=false
            -Dcom.sun.management.jmxremote.ssl=false -Dcassandra.jmx.remote.port=7201
        - CASSANDRA_BROADCAST_RPC_ADDRESS=CompuAndre.local
        - CASSANDRA_BROADCAST_ADDRESS=CompuAndre.local
        - LOCAL_JMX=no
        volumes:
        - ./mount/cassandra-node-1:/var/lib/cassandra
        - ./mount/cassandra-node-1/certs:/etc/cassandra/certs
        - ./mount/cassandra-node-1/cassandra.yaml:/etc/cassandra/cassandra.yaml
        - ./mount/cassandra-node-1/cassandra-rackdc.properties:/etc/cassandra/cassandra-rackdc.properties
        - ./mount/jmxremote.password:/etc/cassandra/jmxremote.password
        networks:
        - cassandra-cluster
        ports:
        - 9041:9041
        - 7001:7001
        - 7501:7501
        - 7201:7201
        extra_hosts:
        - host.docker.internal:host-gateway
#        dns: &id001
#        - 10.15.30.1
        deploy:
            resources:
                limits:
                    cpus: '2.0'
                    memory: 1G
        healthcheck:
            test:
            - CMD-SHELL
            - env JVM_OPTS= nodetool -u cassandra -pw cassandra status | grep UN ||
                exit 1
            interval: 5s
            timeout: 10s
            retries: 24
            start_period: 20s
        depends_on: {}
    cassandra-node-2:
        image: cassandra:5.0
        container_name: cassandra-node-2
        environment:
        - CASSANDRA_USER=cassandra
        - MAX_HEAP_SIZE=768M
        - HEAP_NEWSIZE=256M
        - CASSANDRA_CLUSTER_NAME=cassandra-cluster.rgorosti.local
        - CASSANDRA_SEEDS=CompuAndre.local:7001,CompuAndre.local:7002,CompuAndre.local:7003
        - CASSANDRA_LISTEN_ADDRESS=auto
        - CASSANDRA_RPC_ADDRESS=0.0.0.0
        - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
        - CASSANDRA_NATIVE_TRANSPORT_PORT=9042
        - CASSANDRA_STORAGE_PORT=7002
        - CASSANDRA_SSL_STORAGE_PORT=7502
        - JVM_OPTS=-Xms256M -Xmx768M -Dcassandra.native_transport_port=9042 -Dcassandra.storage_port=7002
            -Dcassandra.ssl_storage_port=7502 -Dcassandra.broadcast_rpc_address=CompuAndre.local
            -Dcassandra.broadcast_address=CompuAndre.local -Dcom.sun.management.jmxremote.authenticate=false
            -Dcom.sun.management.jmxremote.ssl=false -Dcassandra.jmx.remote.port=7202
        - CASSANDRA_BROADCAST_RPC_ADDRESS=CompuAndre.local
        - CASSANDRA_BROADCAST_ADDRESS=CompuAndre.local
        - LOCAL_JMX=no
        volumes:
        - ./mount/cassandra-node-2:/var/lib/cassandra
        - ./mount/cassandra-node-2/certs:/etc/cassandra/certs
        - ./mount/cassandra-node-2/cassandra.yaml:/etc/cassandra/cassandra.yaml
        - ./mount/cassandra-node-2/cassandra-rackdc.properties:/etc/cassandra/cassandra-rackdc.properties
        - ./mount/jmxremote.password:/etc/cassandra/jmxremote.password
        networks:
        - cassandra-cluster
        ports:
        - 9042:9042
        - 7002:7002
        - 7502:7502
        - 7202:7202
        extra_hosts:
        - host.docker.internal:host-gateway
        dns: *id001
        deploy:
            resources:
                limits:
                    cpus: '2.0'
                    memory: 1G
        healthcheck:
            test:
            - CMD-SHELL
            - env JVM_OPTS= nodetool -u cassandra -pw cassandra status | grep UN ||
                exit 1
            interval: 5s
            timeout: 10s
            retries: 24
            start_period: 20s
        depends_on:
            cassandra-node-1:
                condition: service_started
    cassandra-node-3:
        image: cassandra:5.0
        container_name: cassandra-node-3
        environment:
        - CASSANDRA_USER=cassandra
        - MAX_HEAP_SIZE=768M
        - HEAP_NEWSIZE=256M
        - CASSANDRA_CLUSTER_NAME=cassandra-cluster.rgorosti.local
        - CASSANDRA_SEEDS=CompuAndre.local:7001,CompuAndre.local:7002,CompuAndre.local:7003
        - CASSANDRA_LISTEN_ADDRESS=auto
        - CASSANDRA_RPC_ADDRESS=0.0.0.0
        - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
        - CASSANDRA_NATIVE_TRANSPORT_PORT=9043
        - CASSANDRA_STORAGE_PORT=7003
        - CASSANDRA_SSL_STORAGE_PORT=7503
        - JVM_OPTS=-Xms256M -Xmx768M -Dcassandra.native_transport_port=9043 -Dcassandra.storage_port=7003
            -Dcassandra.ssl_storage_port=7503 -Dcassandra.broadcast_rpc_address=CompuAndre.local
            -Dcassandra.broadcast_address=CompuAndre.local -Dcom.sun.management.jmxremote.authenticate=false
            -Dcom.sun.management.jmxremote.ssl=false -Dcassandra.jmx.remote.port=7203
        - CASSANDRA_BROADCAST_RPC_ADDRESS=CompuAndre.local
        - CASSANDRA_BROADCAST_ADDRESS=CompuAndre.local
        - LOCAL_JMX=no
        volumes:
        - ./mount/cassandra-node-3:/var/lib/cassandra
        - ./mount/cassandra-node-3/certs:/etc/cassandra/certs
        - ./mount/cassandra-node-3/cassandra.yaml:/etc/cassandra/cassandra.yaml
        - ./mount/cassandra-node-3/cassandra-rackdc.properties:/etc/cassandra/cassandra-rackdc.properties
        - ./mount/jmxremote.password:/etc/cassandra/jmxremote.password
        networks:
        - cassandra-cluster
        ports:
        - 9043:9043
        - 7003:7003
        - 7503:7503
        - 7203:7203
        extra_hosts:
        - host.docker.internal:host-gateway
        dns: *id001
        deploy:
            resources:
                limits:
                    cpus: '2.0'
                    memory: 1G
        healthcheck:
            test:
            - CMD-SHELL
            - env JVM_OPTS= nodetool -u cassandra -pw cassandra status | grep UN ||
                exit 1
            interval: 5s
            timeout: 10s
            retries: 24
            start_period: 20s
        depends_on:
            cassandra-node-1:
                condition: service_started
            cassandra-node-2:
                condition: service_started
networks:
    cassandra-cluster:
        driver: bridge
